# Generated by Django 3.2.5 on 2021-07-05 06:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('xp', models.IntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('tress_unlocked', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
