# Generated by Django 3.2.5 on 2021-07-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='discord_id',
        ),
    ]
